### ISSUE TITLE
Problems parsing RMC

### ISSUE THREAD

**Issue by jtornero** [Knio/pynmea2#43]
@Knio Hello,

I have some trouble parsing an RMC sentence (pynmea2 1.4.2 installed through pip):

p.parse('$GPRMC,114130,A,3809.1250,N,02415.8050,E,12195.6,341.5,280915,5,E,A*1\r\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pynmea2/nmea.py", line 106, in parse
    raise ParseError('could not parse data: %r' % line)
pynmea2.nmea.ParseError: could not parse data: '$GPRMC,114130,A,3809.1250,N,02415.8050,E,12195.6,341.5,280915,5,E,A*1\r\n'

But if I try to parse:

p.parse('$GPRMC,114130,A,3809.1250,N,02415.8050,E,12195.6,341.5,280915,5,E\r\n')

That's the nmea sentence without the checksum field

I get (almost) the correct parsing:

<RMC(timestamp=datetime.time(11, 41, 30), status='A', lat='3809.1250', lat_dir='N', lon='02415.8050', 
lon_dir='E', spd_over_grnd=12195.6, true_course=341.5, datestamp=datetime.date(2015, 9, 28), mag_variation='5', mag_var_dir='E\r\n')>

(notice the last field with \r\n characters)

anyway, parsing a GGA sentence both with checksum and newline chars is ok:

p.parse('$GPGGA,114130,3809.1250,N,02415.8050,E,1,04,5.6,1500.0,M,34.5,M,,*7E\r\n')
<GGA(timestamp=datetime.time(11, 41, 30), lat='3809.1250', lat_dir='N', lon='02415.8050', lon_dir='E', gps_qual=1, num_sats='04', horizontal_dil='5.6', altitude=1500.0, altitude_units='M', geo_sep='34.5', geo_sep_units='M', age_gps_data='', ref_station_id='')>

What could I do? Thanks

**Comment by jtornero** [comment]
@Knio Sorry I forgot to check one logical thing - Checksum computation is wrong in the gps simulator I am using, your code is OK. Sorry  for the annoyance.

Cheers,

Jorge Tornero
